from .base import *

DEBUG = False

ALLOWED_HOSTS = split_env_list(config('ALLOWED_HOSTS', default=''))

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
